[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    mikalhart/TinyGPSPlus
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    https://github.com/Taylor-eOS/DisplayTerminal.git
;build_flags =
;    -D ARDUINO_USB_MODE=1
;    -D ARDUINO_USB_CDC_ON_BOOT=1
build_flags = 
    -D GPS_RX_PIN=4
    -D GPS_TX_PIN=33

[env:test]
build_src_filter = +<../src/test/*>
[env:display]
build_src_filter = +<../src/display/*>
[env:in_place]
build_src_filter = -<*> +<in_place/*>
